# Generated by Django 6.0.2 on 2026-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS_RADAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Radar Fijo'), ('MOVIL', 'Zona de Radar Móvil')], default='FIJO', max_length=10),
        ),
        migrations.AlterField(
            model_name='radar',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='radar',
            name='velocidad',
            field=models.IntegerField(default=0),
        ),
    ]
